language: php

php:
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover clover.xml

after_script:
  - vendor/bin/coveralls
